const $=id=>document.getElementById(id);
const num=new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2});
const money=n=>num.format(n)+' ₽';
const qty=(id,n)=>n===null?'Домашняя база':num.format(n)+' '+ingredients[id].unit;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const activeTier=1;
let activeWeek=0,lastTrigger=null;
const expandedShopping=new Set();
const view=typeof location==='undefined'?'all':new URLSearchParams(location.search).get('view')||'all';
if(['shopping','stock','expenses'].includes(view))document.documentElement.dataset.view=view;
if(typeof location!=='undefined'&&location.search.includes('embed=1'))document.documentElement.classList.add('embedded');
const key='petersburg-ration-september-2026-v2';
let saved={grains:{},entries:[]},storageOK=true;
try{const raw=JSON.parse(localStorage.getItem(key)||'null');if(raw&&typeof raw==='object'){if(raw.grains&&typeof raw.grains==='object')saved.grains=Object.fromEntries(['rice','bulgur','couscous'].filter(k=>Number.isFinite(raw.grains[k])&&raw.grains[k]>=0&&raw.grains[k]<=5000).map(k=>[k,raw.grains[k]]));if(Array.isArray(raw.entries))saved.entries=raw.entries.filter(x=>x&&typeof x.name==='string'&&x.name.length<=140&&Number.isFinite(x.amount)&&x.amount>0&&x.amount<=100000&&/^\d{4}-\d{2}-\d{2}$/.test(x.date)&&['review','w0','w1','w2','w3'].includes(x.period)).map(x=>({name:x.name,amount:x.amount,date:x.date,period:x.period}));}}catch{storageOK=false;}
function persist(){try{localStorage.setItem(key,JSON.stringify(saved));storageOK=true;return true;}catch{storageOK=false;return false;}}
function plan(){return calculate(activeTier,saved.grains);}
const chip=(label,value)=>`<span class="chip">${label}: ${value}</span>`;
function dateFor(w,index){const d=new Date(weeks[w].date+'T12:00:00');d.setDate(d.getDate()+slots[index][2]);return d.toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit'});}
function renderDashboard(){const p=plan();$('dashboard').innerHTML=chip('Лимит на недели 5–8',money(25000))+chip('План с резервами',money(p.total));}
function renderMenu(){const w=weeks[activeWeek];$('week-tabs').innerHTML=weeks.map((w,i)=>`<button type="button" data-week="${i}" class="${activeWeek===i?'active':''}" aria-pressed="${activeWeek===i}">Неделя ${i+5} · ${w.label}</button>`).join('');$('week-heading').innerHTML=`<div class="week-heading"><h3>${w.theme}</h3><span class="tag">Все блюда запланированы</span></div>`;$('meal-list').innerHTML=w.ids.map((id,i)=>{const r=recipeFor(id,activeTier),cal=calories(r);return `<button class="meal-card ${i>=5?'weekend':''}" type="button" data-recipe="${id}" aria-haspopup="dialog"><span class="meal-top"><span>${slots[i][0]} · ${dateFor(activeWeek,i)} · ${slots[i][1]}</span><span class="tag">${i>=5?'Гибкий план':r.protein}</span></span><span class="meal-title">${esc(r.title)}</span><span class="meal-footer">≈ ${cal} ккал / человеку · ${r.time} мин →</span><small>${portionLabel(r)}${i<5?` · с обедом 1 300: ≈ ${cal+1300} ккал*`:''}</small></button>`;}).join('');$('week-prep').innerHTML=`<h3>Подготовка</h3><p>${activeWeek===0?'Сначала используйте пригодные остатки. Курицу отмерьте по 570 г на понедельник и четверг; имеющиеся 760 г уже вычтены, докупка — 400 г. Йогурта на эти и остальные будничные блюда нужно 750 г: 500 г дома и 250 г к покупке. Обед первого понедельника из прежнего воскресенья не подтверждён.':'При покупке разделите мясо по рецептам. Грибы для более позднего блюда можно предварительно приготовить и заморозить без соуса. Овощи для салата режьте только перед едой.'}</p><p>*Сумма рабочего обеда и ужина парня, не вся еда за день.</p>`;$('extras').innerHTML=extras(activeTier,activeWeek).map(e=>`<div class="extra"><strong>${e.title}</strong><p>${e.how}</p><small>На неделю: ${Object.entries(e.items).map(([id,q])=>`${ingredients[id].name.toLowerCase()} ${qty(id,q)}`).join('; ')}.</small></div>`).join('');}
const purchaseDates=['6–7 сентября','13 сентября','20 сентября','27 сентября'];
function renderShopping(){
 const p=plan();
 $('shopping-weeks').innerHTML=p.weeks.map((week,index)=>{
  const rows=week.rows.filter(r=>!ingredients[r.id].base).sort((a,b)=>ingredients[a.id].name.localeCompare(ingredients[b.id].name,'ru'));
  const buying=rows.filter(r=>r.purchase>0);
  const grainWarning=id=>['rice','bulgur','couscous'].includes(id)&&!(id in saved.grains);
  return `<details class="shopping-week surface" data-shopping-week="${index}" ${expandedShopping.has(index)?'open':''}>
  <summary><span><strong>Неделя ${index+5}</strong><small>${weeks[index].label} · ${buying.length} позиций к покупке</small></span><span class="week-price">${money(week.total)}<small>План с резервами</small></span><span class="disclosure-icon" aria-hidden="true">⌄</span></summary>
  <div class="shopping-week-content"><h3>Что купить на неделю ${index+5}</h3><p class="buy-explanation">«Купить» — только недостающее после вычета запасов, с округлением до фасовки. Цена — за всё количество к покупке.${index>0?' Остатки будущих недель — прогноз по меню.':' Учтён ваш список остатков от 06.09.'}</p><div class="buy-columns" aria-hidden="true"><span>Продукт</span><span>Купить</span><span>Цена</span></div>
  <ul class="buy-list">${buying.map(r=>{const i=ingredients[r.id];return `<li data-buy-product="${r.id}"><div class="buy-product"><strong>${i.name}</strong></div><div class="buy-quantity"><span class="sr-only">Купить: </span><strong>${qty(r.id,r.purchase)}</strong></div><div class="buy-price"><span class="sr-only">Плановая цена: </span><strong>${money(r.cost)}</strong></div>${grainWarning(r.id)?'<p class="buy-warning">Сначала взвесьте домашний остаток: его неизвестные граммы пока не вычтены.</p>':''}${r.id==='banana'?'<p class="buy-hint">Указана мякоть; с кожурой берите примерно в 1,5 раза больше.</p>':''}</li>`}).join('')}</ul>
  <div class="shopping-actions"><button type="button" class="utility" data-download-week="${index}">Скачать список недели ${index+5}</button><span>Основная закупка: ${purchaseDates[index]}</span></div>
  <div class="chips">${chip('Продукты',money(week.food))}${chip('Покупаем сами','без доставки')}${chip('База · резерв',money(week.base))}${chip('5% на цены',money(week.buffer))}</div>
  <p class="muted">Цены плановые, не факт оплаты. Перед походом в магазин проверьте остатки и планы на выходные.${week.base?' На пополнение масла, муки, сахара и прочей базы зарезервировано 800 ₽; покупайте только недостающее.':''}</p>
  <details class="calculation-details"><summary>Подробный расчёт: фасовка, остатки и блюда</summary>
  <div class="table-scroll"><table><caption class="sr-only">Расчёт недели ${index+5}</caption><thead><tr><th scope="col">Продукт</th><th scope="col">Купить</th><th scope="col">Цена</th><th scope="col">Нужно</th><th scope="col">Есть</th><th scope="col">Останется</th></tr></thead><tbody>
  ${rows.map(r=>`<tr><td><strong>${ingredients[r.id].name}</strong><small>Фасовка: ${qty(r.id,ingredients[r.id].pack)} · ${money(ingredients[r.id].price)}${r.purchase?`; купить ${num.format(r.purchase/ingredients[r.id].pack)} уп. / мерных долей`:''}.</small><details><summary>Куда идёт</summary><ul>${r.alloc.map(([name,n])=>`<li>${esc(name)}: ${qty(r.id,n)}</li>`).join('')}</ul></details></td><td>${r.purchase?qty(r.id,r.purchase):'Не нужно'}</td><td>${r.cost?money(r.cost):'—'}</td><td>${qty(r.id,r.used)}</td><td>${grainWarning(r.id)?'Неизвестно + ':''}${qty(r.id,r.opening)}</td><td>${qty(r.id,r.closing)}</td></tr>`).join('')}
  </tbody></table></div><h4>Расход домашней базы</h4><ul>${week.rows.filter(r=>ingredients[r.id].base).map(r=>`<li>${ingredients[r.id].name}: ${qty(r.id,r.used)}</li>`).join('')}</ul><p class="muted">Остаток после недели — прогноз. Переносить скоропортящееся можно только в пределах срока или после подходящей заморозки.</p></details></div></details>`;
 }).join('');
 $('shopping-budget').innerHTML=chip('Лимит цикла',money(25000))+chip('Все 4 закупки с резервами',money(p.total));
}
function renderStock(){$('stock-list').innerHTML=Object.values(ingredients).filter(i=>i.stock>0).map(i=>`<div class="stock-item">${i.name}<strong>${qty(i.id,i.stock)}</strong></div>`).join('')+`<div class="stock-item">Белая фасоль<strong>2 банки · вес неизвестен</strong></div><div class="stock-item">Кетчуп<strong>1 упаковка · вес неизвестен</strong></div><div class="stock-item">Рис / булгур / кускус<strong>8 / 5 / 1 пакетик</strong></div>`;$('stock-notes').innerHTML=stockNotes.map(s=>`<li>${s}</li>`).join('');for(const id of ['rice','bulgur','couscous'])$('grain-form').elements.namedItem(id).value=saved.grains[id]??'';}
function openRecipe(id,trigger){const r=recipeFor(id,activeTier);lastTrigger=trigger;$('recipe-eyebrow').textContent=`Неделя ${activeWeek+5} · ${tiers[activeTier].name}`;$('recipe-title').textContent=r.title;$('recipe-meta').innerHTML=chip('Порции',String(r.portions))+chip('Время',r.time+' мин')+chip('Калории',`≈ ${calories(r)} на человека`);$('recipe-ingredients-title').textContent='Ингредиенты на '+r.portions+' порции';$('recipe-ingredients').innerHTML=Object.entries(r.items).map(([id,q])=>`<li><span>${ingredients[id].name}</span><strong>${qty(id,q)}</strong></li>`).join('');$('recipe-steps').innerHTML=r.steps.map(s=>`<li>${esc(s)}</li>`).join('');$('recipe-note').textContent=r.note||S;const d=$('recipe-dialog');if(typeof d.showModal==='function')d.showModal();else d.setAttribute('open','');document.body.style.overflow='hidden';$('recipe-close').focus();}
function closeRecipe(){const d=$('recipe-dialog');if(typeof d.close==='function')d.close();else d.removeAttribute('open');document.body.style.overflow='';lastTrigger?.focus();}
const seed=[{period:'review',name:'Ранее учтённая корзина недели 4: чек 29.08 + отдельные фрукты и молоко',amount:4165.51,date:'Неделя 31.08–06.09',source:'сохранённый журнал сайта'},{period:'review',name:'Яйца, 10 шт.',amount:130,date:'Сообщено 06.09',source:'со слов пользователя'},{period:'review',name:'Яблоки, корица, разрыхлитель, тесто',amount:780,date:'Сообщено 06.09',source:'единая сумма со слов пользователя'}];
function renderExpenses(){const period=$('expense-period').value;const all=[...seed,...saved.entries.map(x=>({...x,source:'ручная запись в этом браузере'}))].filter(x=>x.period===period);const total=all.reduce((s,x)=>s+x.amount,0);const week=Number(period.slice(1));const comparison=period==='review'?'Сохранённые покупки недели 4':`План недели: ${money(plan().weeks[week].total)}`;$('expense-summary').innerHTML=chip('Внесено',money(total))+chip('Статус',comparison)+chip('Полнота',period==='review'?'детализировано по сообщениям':'проверить по чекам');$('expense-list').innerHTML=all.length?all.map(x=>`<div class="expense-row"><div>${esc(x.name)}<small>${esc(x.date)} · ${esc(x.source)}</small></div><strong>${money(x.amount)}</strong></div>`).join(''):'<p class="muted">Подтверждённых расходов пока нет. Это не означает, что неделя обошлась в 0 ₽.</p>';}
function download(name,data,type){const u=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function render(){renderDashboard();renderMenu();renderShopping();renderExpenses();}
$('week-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-week]');if(b){activeWeek=Number(b.dataset.week);render();}});
$('meal-list').addEventListener('click',e=>{const b=e.target.closest('[data-recipe]');if(b)openRecipe(b.dataset.recipe,b);});
$('recipe-close').addEventListener('click',closeRecipe);$('recipe-dialog').addEventListener('cancel',e=>{e.preventDefault();closeRecipe();});$('recipe-dialog').addEventListener('click',e=>{if(e.target===$('recipe-dialog')){const rect=e.target.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)closeRecipe();}});
$('grain-form').addEventListener('submit',e=>{e.preventDefault();for(const id of ['rice','bulgur','couscous']){const v=e.target.elements.namedItem(id).value;if(v==='')delete saved.grains[id];else saved.grains[id]=Number(v);}persist();render();$('grain-status').textContent=storageOK?'Расчёт обновлён. Веса сохранены в этом браузере.':'Расчёт обновлён, но браузер не разрешил сохранение. Выгрузите JSON.';});
$('expense-period').addEventListener('change',renderExpenses);
$('expense-form').addEventListener('submit',e=>{e.preventDefault();const f=e.target.elements;const amount=Number(f.namedItem('amount').value),name=f.namedItem('name').value.trim(),date=f.namedItem('date').value;if(!name||!Number.isFinite(amount)||amount<=0||!date)return;saved.entries.push({name,amount:Math.round(amount*100)/100,date,period:$('expense-period').value});persist();renderExpenses();f.namedItem('name').value='';f.namedItem('amount').value='';$('expense-status').textContent=storageOK?'Добавлено. Запись хранится только в этом браузере.':'Добавлено на эту страницу; сохранение недоступно. Выгрузите JSON до закрытия.';});
function downloadShopping(weekIndex){const p=plan().weeks[weekIndex];const cell=v=>'"'+String(v).replaceAll('"','""')+'"';const lines=[['Период',weeks[weekIndex].label,'Лимит',tiers[activeTier].cap],['Продукт','Нужно','Есть по расчёту','Купить','Плановая стоимость ₽','Остаток','Куда идёт'],...p.rows.map(r=>[ingredients[r.id].name,qty(r.id,r.used),qty(r.id,r.opening),qty(r.id,r.purchase),r.cost,qty(r.id,r.closing),r.alloc.map(([s,q])=>s+': '+qty(r.id,q)).join(' | ')]),['Доставка (покупаем сами)','','','',0],['База · резерв','','','',p.base],['5% на цены','','','',p.buffer],['ИТОГО план','','','',p.total]];download(`zakupka-nedelya-${weekIndex+5}-${tiers[activeTier].cap}.csv`,'\ufeff'+lines.map(row=>row.map(cell).join(';')).join('\r\n'),'text/csv;charset=utf-8');}
$('export-journal').addEventListener('click',()=>{let legacy=null;try{legacy=JSON.parse(localStorage.getItem('petersburg-ration-actual-week-expenses-v1')||'null');}catch{}download('zhurnal-pitaniya-2026-09.json',JSON.stringify({period,exportedAt:new Date().toISOString(),confirmed:seed,local:saved,legacy,notice:'Расходы разных периодов не объединены. Веса круп внесены пользователем в браузере.'},null,2),'application/json');});
$('print').addEventListener('click',()=>window.print());
$('expense-form').elements.namedItem('date').value=new Date().toLocaleDateString('en-CA');
try{if(localStorage.getItem('petersburg-ration-actual-week-expenses-v1'))$('legacy-note').innerHTML='<p class="notice">В этом браузере есть старый журнал. Он сохранён отдельно и войдёт в выгрузку JSON; его записи не приписаны новой неделе.</p>';}catch{}
renderStock();render();

$('shopping-weeks').addEventListener('click',event=>{const button=event.target.closest('[data-download-week]');if(button)downloadShopping(Number(button.dataset.downloadWeek));});
$('shopping-weeks').addEventListener('toggle',event=>{const card=event.target;if(card.dataset.shoppingWeek===undefined)return;const index=Number(card.dataset.shoppingWeek);if(card.open)expandedShopping.add(index);else expandedShopping.delete(index);},true);
function reportFrameSize(){if(typeof window.parent==='undefined'||window.parent===window||typeof location==='undefined')return;window.parent.postMessage({type:'nutrition-frame-size',height:Math.ceil(document.body.scrollHeight+24)},location.origin);}
if(typeof ResizeObserver!=='undefined')new ResizeObserver(reportFrameSize).observe(document.body);
