const $=id=>document.getElementById(id);
const num=new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2});
const money=n=>num.format(n)+' ₽';
const qty=(id,n)=>n===null?'Домашняя база':num.format(n)+' '+ingredients[id].unit;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let activeTier=1,activeWeek=0,lastTrigger=null;
if(typeof location!=='undefined'&&location.search.includes('embed=1'))document.documentElement.classList.add('embedded');
const key='petersburg-ration-september-2026-v2';
let saved={grains:{},entries:[]},storageOK=true;
try{const raw=JSON.parse(localStorage.getItem(key)||'null');if(raw&&typeof raw==='object'){if(raw.grains&&typeof raw.grains==='object')saved.grains=Object.fromEntries(['rice','bulgur','couscous'].filter(k=>Number.isFinite(raw.grains[k])&&raw.grains[k]>=0&&raw.grains[k]<=5000).map(k=>[k,raw.grains[k]]));if(Array.isArray(raw.entries))saved.entries=raw.entries.filter(x=>x&&typeof x.name==='string'&&x.name.length<=140&&Number.isFinite(x.amount)&&x.amount>0&&x.amount<=100000&&/^\d{4}-\d{2}-\d{2}$/.test(x.date)&&['review','w0','w1','w2','w3'].includes(x.period)).map(x=>({name:x.name,amount:x.amount,date:x.date,period:x.period}));}}catch{storageOK=false;}
function persist(){try{localStorage.setItem(key,JSON.stringify(saved));storageOK=true;return true;}catch{storageOK=false;return false;}}
function plan(){return calculate(activeTier,saved.grains);}
const chip=(label,value)=>`<span class="chip">${label}: ${value}</span>`;
function dateFor(w,index){const d=new Date(weeks[w].date+'T12:00:00');d.setDate(d.getDate()+slots[index][2]);return d.toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit'});}
function renderDashboard(){const p=plan(),t=tiers[activeTier];$('budget-switch').innerHTML=tiers.map((t,i)=>`<button type="button" data-tier="${i}" class="${i===activeTier?'active':''}" aria-pressed="${i===activeTier}">${num.format(t.cap)} ₽</button>`).join('');$('tier-copy').textContent=t.copy;const delivery=p.weeks.reduce((s,w)=>s+w.delivery,0),base=p.weeks.reduce((s,w)=>s+w.base,0),buffer=p.weeks.reduce((s,w)=>s+w.buffer,0);const max=Math.max(...p.weeks.map(w=>w.total));$('dashboard').innerHTML=`<article class="surface padded"><span class="eyebrow">План будущих покупок · 4 недели</span><div class="summary-top"><div><strong class="big-number">${money(p.total)}</strong><small>из лимита ${money(t.cap)}, с резервами</small></div><span class="buffer">Свободно ${money(t.cap-p.total)}</span></div><div class="meter" aria-label="${Math.round(p.total/t.cap*100)} процентов лимита"><span style="width:${Math.min(100,p.total/t.cap*100)}%"></span></div><div class="breakdown"><div><strong>${money(p.food)}</strong><span>Список продуктов</span></div><div><strong>${money(delivery)}</strong><span>Доставка · резерв</span></div><div><strong>${money(base)}</strong><span>База · резерв</span></div><div><strong>${money(buffer)}</strong><span>10% на цены</span></div></div></article><article class="surface padded"><h3>Как распределены покупки</h3><small>Не четыре одинаковых конверта: первая неделя использует запасы.</small><div class="bars" role="img" aria-label="${p.weeks.map((w,i)=>`Неделя ${i+1}: ${money(w.total)}`).join('; ')}">${p.weeks.map((w,i)=>`<div class="bar-col"><div class="bar ${i===activeWeek?'current':''}" style="height:${w.total/max*95}px"><b>${money(w.total)}</b></div><small>Неделя ${i+1}</small></div>`).join('')}</div></article>`;}
function renderMenu(){const w=weeks[activeWeek];$('week-tabs').innerHTML=weeks.map((w,i)=>`<button type="button" data-week="${i}" class="${activeWeek===i?'active':''}" aria-pressed="${activeWeek===i}">Неделя ${i+1} · ${w.label}</button>`).join('');$('week-heading').innerHTML=`<div class="week-heading"><h3>${w.theme}</h3><span class="tag">Все блюда запланированы</span></div>`;$('meal-list').innerHTML=w.ids.map((id,i)=>{const r=recipeFor(id,activeTier),cal=calories(r);return `<button class="meal-card ${i>=5?'weekend':''}" type="button" data-recipe="${id}" aria-haspopup="dialog"><span class="meal-top"><span>${slots[i][0]} · ${dateFor(activeWeek,i)} · ${slots[i][1]}</span><span class="tag">${i>=5?'Гибкий план':r.protein}</span></span><span class="meal-title">${esc(r.title)}</span><span class="meal-footer">≈ ${cal} ккал / человеку · ${r.time} мин →</span><small>2 порции${i<5?` · с обедом 1 300: ≈ ${cal+1300} ккал*`:''}</small></button>`;}).join('');$('week-prep').innerHTML=`<h3>Подготовка</h3><p>${activeWeek===0?'До среды используйте фетаксу, шпинат, 4 помидора и 600 г свежих огурцов. Курицу разделите на 380 + 380 г. Йогурт: 100 + 100 + 100 + 200 г. Вторую банку открывайте в четверг.':'При покупке разделите мясо по рецептам. Грибы для более позднего блюда можно предварительно приготовить и заморозить без соуса. Овощи для салата режьте только перед едой.'}</p><p>*Сумма рабочего обеда и ужина парня, не вся еда за день.</p>`;$('extras').innerHTML=extras(activeTier,activeWeek).map(e=>`<div class="extra"><strong>${e.title}</strong><p>${e.how}</p><small>На неделю: ${Object.entries(e.items).map(([id,q])=>`${ingredients[id].name.toLowerCase()} ${qty(id,q)}`).join('; ')}.</small></div>`).join('');}
const purchaseDates=['6–7 сентября','13 сентября','20 сентября','27 сентября'];
function renderShopping(){const p=plan().weeks[activeWeek];$('shopping-heading').textContent=`Неделя ${activeWeek+1} · основной заказ / поездка: ${purchaseDates[activeWeek]}. В пятницу проверьте планы на выходные.`;$('shopping-totals').innerHTML=chip('Продукты',money(p.food))+chip('Доставка · резерв',money(p.delivery))+chip('База · резерв',money(p.base))+chip('10% на цены',money(p.buffer))+chip('Всего на неделю',money(p.total));const sorted=p.rows.filter(r=>!ingredients[r.id].base).sort((a,b)=>ingredients[a.id].name.localeCompare(ingredients[b.id].name,'ru'));$('shopping-rows').innerHTML=sorted.map(r=>{const i=ingredients[r.id],grain=['rice','bulgur','couscous'].includes(r.id)&&!(r.id in saved.grains);return `<tr><td><strong>${i.name}</strong><small>${money(i.price)} / ${qty(r.id,i.pack)} · оценка${grain?' · сначала сверить пакетики':''}</small><details><summary>Куда идёт · ${r.alloc.length}</summary><ul class="allocation">${r.alloc.map(([label,q])=>`<li>${esc(label)}: <strong>${qty(r.id,q)}</strong></li>`).join('')}</ul></details></td><td>${qty(r.id,r.used)}</td><td>${grain?'Неизвестно + ':''}${qty(r.id,r.opening)}${grain?'<small>Старые пакетики пока не вычтены</small>':''}</td><td><strong>${r.purchase?qty(r.id,r.purchase):'Не нужно'}</strong>${r.purchase?`<small>${num.format(r.purchase/i.pack)} × ${qty(r.id,i.pack)}</small>`:''}</td><td>${r.cost?money(r.cost):'—'}</td><td>${qty(r.id,r.closing)}<small>Прогноз, не факт</small></td></tr>`;}).join('');$('base-use').innerHTML=`<ul>${p.rows.filter(r=>ingredients[r.id].base).map(r=>`<li><strong>${ingredients[r.id].name}: ${qty(r.id,r.used)}</strong><details><summary>Распределение</summary><ul>${r.alloc.map(([label,q])=>`<li>${esc(label)}: ${qty(r.id,q)}</li>`).join('')}</ul></details></li>`).join('')}</ul>`;}
function renderStock(){$('stock-list').innerHTML=Object.values(ingredients).filter(i=>i.stock>0).map(i=>`<div class="stock-item">${i.name}<strong>${qty(i.id,i.stock)}</strong></div>`).join('')+`<div class="stock-item">Белая фасоль<strong>2 банки · вес неизвестен</strong></div><div class="stock-item">Кетчуп<strong>1 упаковка · вес неизвестен</strong></div><div class="stock-item">Рис / булгур / кускус<strong>8 / 5 / 1 пакетик</strong></div>`;$('stock-notes').innerHTML=stockNotes.map(s=>`<li>${s}</li>`).join('');for(const id of ['rice','bulgur','couscous'])$('grain-form').elements.namedItem(id).value=saved.grains[id]??'';}
function openRecipe(id,trigger){const r=recipeFor(id,activeTier);lastTrigger=trigger;$('recipe-eyebrow').textContent=`Неделя ${activeWeek+1} · ${tiers[activeTier].name}`;$('recipe-title').textContent=r.title;$('recipe-meta').innerHTML=chip('Порции','2')+chip('Время',r.time+' мин')+chip('Калории',`≈ ${calories(r)} на человека`);$('recipe-ingredients').innerHTML=Object.entries(r.items).map(([id,q])=>`<li><span>${ingredients[id].name}</span><strong>${qty(id,q)}</strong></li>`).join('');$('recipe-steps').innerHTML=r.steps.map(s=>`<li>${esc(s)}</li>`).join('');$('recipe-note').textContent=r.note||S;const d=$('recipe-dialog');if(typeof d.showModal==='function')d.showModal();else d.setAttribute('open','');document.body.style.overflow='hidden';$('recipe-close').focus();}
function closeRecipe(){const d=$('recipe-dialog');if(typeof d.close==='function')d.close();else d.removeAttribute('open');document.body.style.overflow='';lastTrigger?.focus();}
const seed=[{period:'review',name:'Ранее учтённая корзина недели 4: чек 29.08 + отдельные фрукты и молоко',amount:4165.51,date:'Неделя 31.08–06.09',source:'сохранённый журнал сайта'},{period:'review',name:'Яйца, 10 шт.',amount:130,date:'Сообщено 06.09',source:'со слов пользователя'},{period:'review',name:'Яблоки, корица, разрыхлитель, тесто',amount:780,date:'Сообщено 06.09',source:'единая сумма со слов пользователя'}];
function renderExpenses(){const period=$('expense-period').value;const all=[...seed,...saved.entries.map(x=>({...x,source:'ручная запись в этом браузере'}))].filter(x=>x.period===period);const total=all.reduce((s,x)=>s+x.amount,0);const week=Number(period.slice(1));const comparison=period==='review'?'Сохранённые покупки недели 4':`План недели: ${money(plan().weeks[week].total)}`;$('expense-summary').innerHTML=chip('Внесено',money(total))+chip('Статус',comparison)+chip('Полнота',period==='review'?'детализировано по сообщениям':'проверить по чекам');$('expense-list').innerHTML=all.length?all.map(x=>`<div class="expense-row"><div>${esc(x.name)}<small>${esc(x.date)} · ${esc(x.source)}</small></div><strong>${money(x.amount)}</strong></div>`).join(''):'<p class="muted">Подтверждённых расходов пока нет. Это не означает, что неделя обошлась в 0 ₽.</p>';}
const sourceData=[['Яйца','https://lenta.com/product/yajjco-kurinoe-lenta-s0-rossiya-10sht-713213/'],['Молоко','https://lenta.com/product/671969-671969/'],['Творог','https://lenta.com/product/tvorog-5-bez-zmzh-rossiya-200g-579608/'],['Йогурт','https://lenta.com/product/551608-551608/'],['Сыр','https://lenta.com/product/syr-finskijj-ptv-45-bez-zmzh-belarus-200g-550770/'],['Куриное филе','https://lenta.com/product/123265-123265/'],['Индейка','https://lenta.com/product/file-bedra-indejjki-ohl-gvu-rossiya-410g-484545'],['Говяжий фарш','https://lenta.com/product/farsh-govyazhijj-mgs-pf-ohl-rossiya-400g-783249/'],['Свинина','https://lenta.com/product/svinina-podzharka-ohl-rossiya-400g-719258/'],['Печень','https://lenta.com/product/077974-77974/'],['Минтай','https://lenta.com/product/mintajj-file-porcionnoe-zam-rossiya-400g-378416/'],['Тунец','https://lenta.com/product/rybnye-konservy-tunec-rublennyjj-natur-klyuch-bk-kitajj-185g-652687/'],['Креветки','https://lenta.com/product/krevetki-ochishchennye-vm-200300-rossiya-500g-227076/'],['Паста','https://lenta.com/product/makarony-spagetti-gra-vs-rossiya-450g-688121/'],['Сок','https://lenta.com/product/sok-yablochnyjj-tpak-rossiya-1l-1604/']];
function download(name,data,type){const u=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function render(){renderDashboard();renderMenu();renderShopping();renderExpenses();}
$('budget-switch').addEventListener('click',e=>{const b=e.target.closest('[data-tier]');if(b){activeTier=Number(b.dataset.tier);render();}});
$('week-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-week]');if(b){activeWeek=Number(b.dataset.week);render();}});
$('meal-list').addEventListener('click',e=>{const b=e.target.closest('[data-recipe]');if(b)openRecipe(b.dataset.recipe,b);});
$('recipe-close').addEventListener('click',closeRecipe);$('recipe-dialog').addEventListener('cancel',e=>{e.preventDefault();closeRecipe();});$('recipe-dialog').addEventListener('click',e=>{if(e.target===$('recipe-dialog')){const rect=e.target.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)closeRecipe();}});
$('grain-form').addEventListener('submit',e=>{e.preventDefault();for(const id of ['rice','bulgur','couscous']){const v=e.target.elements.namedItem(id).value;if(v==='')delete saved.grains[id];else saved.grains[id]=Number(v);}persist();render();$('grain-status').textContent=storageOK?'Расчёт обновлён. Веса сохранены в этом браузере.':'Расчёт обновлён, но браузер не разрешил сохранение. Выгрузите JSON.';});
$('expense-period').addEventListener('change',renderExpenses);
$('expense-form').addEventListener('submit',e=>{e.preventDefault();const f=e.target.elements;const amount=Number(f.namedItem('amount').value),name=f.namedItem('name').value.trim(),date=f.namedItem('date').value;if(!name||!Number.isFinite(amount)||amount<=0||!date)return;saved.entries.push({name,amount:Math.round(amount*100)/100,date,period:$('expense-period').value});persist();renderExpenses();f.namedItem('name').value='';f.namedItem('amount').value='';$('expense-status').textContent=storageOK?'Добавлено. Запись хранится только в этом браузере.':'Добавлено на эту страницу; сохранение недоступно. Выгрузите JSON до закрытия.';});
$('download-shopping').addEventListener('click',()=>{const p=plan().weeks[activeWeek];const cell=v=>'"'+String(v).replaceAll('"','""')+'"';const lines=[['Период',weeks[activeWeek].label,'Лимит',tiers[activeTier].cap],['Продукт','Нужно','Есть по расчёту','Купить','Плановая стоимость ₽','Остаток','Куда идёт'],...p.rows.map(r=>[ingredients[r.id].name,qty(r.id,r.used),qty(r.id,r.opening),qty(r.id,r.purchase),r.cost,qty(r.id,r.closing),r.alloc.map(([s,q])=>s+': '+qty(r.id,q)).join(' | ')]),['Доставка · резерв','','','',p.delivery],['База · резерв','','','',p.base],['10% на цены','','','',p.buffer],['ИТОГО план','','','',p.total]];download(`zakupka-nedelya-${activeWeek+1}-${tiers[activeTier].cap}.csv`,'\ufeff'+lines.map(row=>row.map(cell).join(';')).join('\r\n'),'text/csv;charset=utf-8');});
$('export-journal').addEventListener('click',()=>{let legacy=null;try{legacy=JSON.parse(localStorage.getItem('petersburg-ration-actual-week-expenses-v1')||'null');}catch{}download('zhurnal-pitaniya-2026-09.json',JSON.stringify({period,exportedAt:new Date().toISOString(),confirmed:seed,local:saved,legacy,notice:'Расходы разных периодов не объединены. Веса круп внесены пользователем в браузере.'},null,2),'application/json');});
$('print').addEventListener('click',()=>window.print());
$('sources').innerHTML=sourceData.map(([label,url])=>`<a href="${url}" target="_blank" rel="noreferrer">Лента · ${label}</a>`).join('');
$('expense-form').elements.namedItem('date').value=new Date().toLocaleDateString('en-CA');
try{if(localStorage.getItem('petersburg-ration-actual-week-expenses-v1'))$('legacy-note').innerHTML='<p class="notice">В этом браузере есть старый журнал. Он сохранён отдельно и войдёт в выгрузку JSON; его записи не приписаны новой неделе.</p>';}catch{}
renderStock();render();
function renderActualReport(){const a=monthActual;$('actual-report').innerHTML=`<div class="expense-top"><article class="surface padded"><span class="eyebrow">Расход цикла ${a.period}</span><strong class="big-number">${money(a.total)}</strong><p>По сохранённым покупкам, включая новые 910 ₽. Вы сообщили округлённый итог около 21 000 ₽.</p><div class="chips">${chip('Ниже лимита',money(a.limit-a.total))}${chip('Отклонение','−17,6%')}</div><small>По округлённым 21 000 ₽ — на 4 000 ₽ / 16% ниже плана. Разница 398,96 ₽ не считается отдельной покупкой.</small></article><article class="surface padded"><span class="eyebrow">Следующий месяц · прогноз</span><h3>Ориентир расходов 22–23 тыс. ₽<br>Лимит с запасом — 25 тыс. ₽</h3><p>Продолжение фактического темпа на 28 дней: 20,6–21 тыс. ₽; с запасом 10% — 22,7–23,1 тыс. ₽. На 30 дней: 22,1–22,5 тыс. ₽ без нового резерва или 24,3–24,8 тыс. ₽ с ним.</p><small>Это сценарий при похожем режиме. Остатки снижают первую закупку, восстановление пропущенных выходных может увеличить расход. Точный новый продуктовый план и его резервы — в дашборде выше.</small></article></div><div class="chips">${a.weeks.map((n,i)=>chip('Неделя '+(i+1),money(n))).join('')}</div><div class="table-scroll"><table><thead><tr><th>Покупали</th><th>Цена за единицу</th><th>Что это значит</th></tr></thead><tbody>${a.comparisons.map(row=>'<tr>'+row.map(c=>'<td>'+esc(c)+'</td>').join('')+'</tr>').join('')}</tbody></table></div><details class="surface details"><summary>Категории и границы анализа</summary><ul>${a.categories.map(([s,n])=>`<li>${s}: ${money(n)} · ${num.format(n/a.total*100)}%</li>`).join('')}</ul><p>Продуктовый факт включает покупки в запас, а не только съеденную еду. Списания, стоимость съеденного, изменение веса и вклад пропусков в экономию не доказаны. Покупки привязаны к неделе меню: например, чек 21–22 августа относился к третьей неделе. Доставка без отдельной подтверждённой строки не оценивается задним числом. Маскарпоне исключён по прежнему решению.</p><p>Источники: сохранённые строки plan-data.ts, price-observations.ts и новое сообщение от 06.09. Первичные файлы чеков не публикуются. При следующих покупках сравниваем одинаковый товар отдельно от аналога.</p></details>`;}
renderActualReport();
